# Publish all joint states -----------------------------------
panther_joint_publisher:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

panther_velocity_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: 'lf_wheel_joint'
  right_wheel: 'rf_wheel_joint'
  publish_rate: 50
  pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
  cmd_vel_timeout: 0.25

  # Base frame_id
  base_frame_id: base_link

  # Odometry fused with IMU is published by robot_localization, so
  # no need to publish a TF based on encoders alone.
  enable_odom_tf: false

  # Panther hardware provides wheel velocities
  estimate_velocity_from_position: false

  # Wheel separation and radius multipliers
  wheel_separation_multiplier:  1 # default: 1.0
  wheel_radius_multiplier:     1 # default: 1.0

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits:     true
      max_velocity:            1.4   # m/s
      has_acceleration_limits: true
      max_acceleration:        2.0   # m/s^2
  angular:
    z:
      has_velocity_limits:     true
      max_velocity:            6.0   # rad/s
      has_acceleration_limits: true
      max_acceleration:        8.0   # rad/s^2
