footprint: [[-0.25, 0.22], [0.25, 0.22], [0.25, -0.22], [-0.25, -0.22]]
footprint_padding: 0.01

robot_base_frame: base_link
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 1.7

resolution: 0.05

obstacle_range: 2.5
raytrace_range: 3.0

#layer definitions
static:
    map_topic: /rtabmap/grid_map
    subscribe_to_updates: true

obstacles_laser:
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: /zed_node/scan}
    livox: {data_type: PointCloud2, clearing: true, marking: true, topic: /pc2_full}
    observation_sources: livox
inflation:
    inflation_radius: 0.4
