footprint: [[-0.25, 0.22], [0.25, 0.22], [0.25, -0.22], [-0.25, -0.22]]
footprint_padding: 0.01

robot_base_frame: base_link
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 2.5
raytrace_range: 3.0

#layer definitions
static:
    map_topic: /rtabmap/proj_map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser 
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: zed_node/scan}

inflation:
    inflation_radius: 0.4
